# Example Config File
log:
    filename: feedhandler.log
    level: WARNING

# Enable UVLoop (if not installed, will not cause errors)
uvloop: True

# Ignore invalid symbols/instruments
ignore_invalid_instruments: False

# Use multiprocessing for backends
backend_multiprocessing: True

# Secrets for exchanges
binance_futures:
    key_id: "zhBF9X2mhD7rY6fpFU243biBtE4ySGpXTBPdYYOExyx27G5CrU6cCEditBhO7ek4"
    key_secret: "6rIYDN1xBaxxGyuLslYGMxlHFtjgzhVh6nV4zO8IKaspdF1H3tC5MKXMgxA1rHDA"
binance_delivery:
    key_id : "zhBF9X2mhD7rY6fpFU243biBtE4ySGpXTBPdYYOExyx27G5CrU6cCEditBhO7ek4"
    key_secret: "6rIYDN1xBaxxGyuLslYGMxlHFtjgzhVh6nV4zO8IKaspdF1H3tC5MKXMgxA1rHDA"
bit.com:
    key_id: null
    key_secret: null
bitget:
    key_id: null
    key_secret: null
    key_passphrase: null
bitmex:
    key_id: null
    key_secret: null
bitfinex:
    key_id: null
    key_secret: null
coinbase:
    key_id: null
    key_secret: null
    key_passphrase: null
deribit:
    key_id: null
    key_secret: null
gemini:
    key_id: null
    key_secret: null
    account_name: null   # this is an optional param needed only when using a master api key
kraken:
    key_id: null
    key_secret: null
kucoin:
    key_id: null
    key_secret: null
    key_passphrase: null
okcoin:
    key_id: null
    key_secret: null
    key_passphrase: null
okx:
    key_id: null
    key_secret: null
    key_passphrase: null
poloniex:
    key_id: null
    key_secret: null
